### ISSUE TITLE
missing requirements in setup.py?

### ISSUE THREAD

**Issue by tkimnguyen** [plone/ploneorg.addonlisting#2]
According to https://community.plone.org/t/bin-instance-fg-gives-error-importerror-no-module-named-requests/ are simplejson and requests missing from setup.py?

**Comment by loechel** [comment]
yes they are missing, they are part of ploneorg.core setup.py so they have never been missing in any development before, as we build on top of ploneorg.core

@pavithirakc might resolve this by adding to install_requires in setup.py and make a pull request to learn the procedures.

**Comment by loechel** [comment]
Fixed with 39b60dbd43e50a7583bba6f088a098352ebdda6f
