### ISSUE TITLE
Implement BrowserViews for addonlisting

### ISSUE THREAD

**Issue by ghost** [plone/ploneorg.addonlisting#7]
- [x] plan the BrowserView for AddOn and AddOnFolder
- [ ] Implement corresponding templates and View classes
- [ ] Document and write tests

**Comment by ghost** [comment]
![addonlisting1](https://cloud.githubusercontent.com/assets/10302949/26391654/336928f4-4081-11e7-87a7-af141787bc1f.png)
The order of listing would be changed to Recommended Add-ons, New Add-ons and then Most Downloaded Add-ons

**Comment by ghost** [comment]
![addon](https://cloud.githubusercontent.com/assets/10302949/26391755/a5f3d388-4081-11e7-8fd1-54b9612e511b.png)
This information would be displayed in a modal, when an addon is selected from the listing and 'view on pypi' link would be added to the details to redirect to the corresponding pypi page.

**Comment by ghost** [comment]
design discussion in the forum
https://community.plone.org/t/plone-addon-listing-design-discussion/4262

**Comment by loechel** [comment]
@pavithirakc we should revisit this issue and look if everything is finished. For me it looks like the Browser View (Design Implementation) for the Addon itself is missing.

That should show up in the modal and if you open the link to the addon directly
